insert into CANDIDATES (name,email,gender,salary_expected,currency,profession,native_language)
values ('Julio Velarde Bazan','veldar.julio@gmail.com','Masculino',5000,'pen','Ingeniero de Software','Español'),
	   ('Sandra Juarez Mendoza','juarez.sandra@gmail.com','Femenino',6000,'pen','Ingeniero de Sistemas','Español'),
       ('Oscar Miguel Plaza','miguel.oscar@gmail.com','Masculino',4000,'usd','Ingeniero de Industrial','Ingles'),
       ('Sarita Flores Daza','flores.sarita@gmail.com','Femenino',6000,'usd','Ingeniero de Sistemas','Portugues'),
       ('Juan Carpio Ortis','carpio.juan@gmail.com','Masculino',8000,'pen','Ingeniero de Software','Español');